steps:
  - name: Send WeChat
    run: |
      curl -s "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=53ab5af5-b293-4dcc-ad40-fc6508c48924" \
      -H "Content-Type: application/json" \
      -d '{
        "msgtype":"text",
        "text":{
          "content":"GitHub自动推送测试成功"
        }
      }'
